const countries = [
    { code: "US", name: "United States", dial_code: "+1", flag: "🇺🇸", flagUrl: `https://flagcdn.com/w20/us.png` },
    { code: "GB", name: "United Kingdom", dial_code: "+44", flag: "🇬🇧", flagUrl: `https://flagcdn.com/w20/gb.png` },
    { code: "CA", name: "Canada", dial_code: "+1", flag: "🇨🇦", flagUrl: `https://flagcdn.com/w20/ca.png` },
    { code: "AU", name: "Australia", dial_code: "+61", flag: "🇦🇺", flagUrl: `https://flagcdn.com/w20/au.png` },
    { code: "NZ", name: "New Zealand", dial_code: "+64", flag: "🇳🇿", flagUrl: `https://flagcdn.com/w20/nz.png` },
    { code: "IN", name: "India", dial_code: "+91", flag: "🇮🇳", flagUrl: `https://flagcdn.com/w20/in.png` },
    { code: "DE", name: "Germany", dial_code: "+49", flag: "🇩🇪", flagUrl: `https://flagcdn.com/w20/de.png` },
    { code: "FR", name: "France", dial_code: "+33", flag: "🇫🇷", flagUrl: `https://flagcdn.com/w20/fr.png` },
    { code: "IT", name: "Italy", dial_code: "+39", flag: "🇮🇹", flagUrl: `https://flagcdn.com/w20/it.png` },
    { code: "ES", name: "Spain", dial_code: "+34", flag: "🇪🇸", flagUrl: `https://flagcdn.com/w20/es.png` },
    { code: "PT", name: "Portugal", dial_code: "+351", flag: "🇵🇹", flagUrl: `https://flagcdn.com/w20/pt.png` },
    { code: "NL", name: "Netherlands", dial_code: "+31", flag: "🇳🇱", flagUrl: `https://flagcdn.com/w20/nl.png` },
    { code: "BE", name: "Belgium", dial_code: "+32", flag: "🇧🇪", flagUrl: `https://flagcdn.com/w20/be.png` },
    { code: "CH", name: "Switzerland", dial_code: "+41", flag: "🇨🇭", flagUrl: `https://flagcdn.com/w20/ch.png` },
    { code: "AT", name: "Austria", dial_code: "+43", flag: "🇦🇹", flagUrl: `https://flagcdn.com/w20/at.png` },
    { code: "SE", name: "Sweden", dial_code: "+46", flag: "🇸🇪", flagUrl: `https://flagcdn.com/w20/se.png` },
    { code: "DK", name: "Denmark", dial_code: "+45", flag: "🇩🇰", flagUrl: `https://flagcdn.com/w20/dk.png` },
    { code: "FI", name: "Finland", dial_code: "+358", flag: "🇫🇮", flagUrl: `https://flagcdn.com/w20/fi.png` },
    { code: "NO", name: "Norway", dial_code: "+47", flag: "🇳🇴", flagUrl: `https://flagcdn.com/w20/no.png` },
    { code: "JP", name: "Japan", dial_code: "+81", flag: "🇯🇵", flagUrl: `https://flagcdn.com/w20/jp.png` },
    { code: "KR", name: "South Korea", dial_code: "+82", flag: "🇰🇷", flagUrl: `https://flagcdn.com/w20/kr.png` },
    { code: "CN", name: "China", dial_code: "+86", flag: "🇨🇳", flagUrl: `https://flagcdn.com/w20/cn.png` },
    { code: "BR", name: "Brazil", dial_code: "+55", flag: "🇧🇷", flagUrl: `https://flagcdn.com/w20/br.png` },
    { code: "ZA", name: "South Africa", dial_code: "+27", flag: "🇿🇦", flagUrl: `https://flagcdn.com/w20/za.png` },
    { code: "MX", name: "Mexico", dial_code: "+52", flag: "🇲🇽", flagUrl: `https://flagcdn.com/w20/mx.png` },
    { code: "AR", name: "Argentina", dial_code: "+54", flag: "🇦🇷", flagUrl: `https://flagcdn.com/w20/ar.png` },
    { code: "CL", name: "Chile", dial_code: "+56", flag: "🇨🇱", flagUrl: `https://flagcdn.com/w20/cl.png` },
    { code: "CO", name: "Colombia", dial_code: "+57", flag: "🇨🇴", flagUrl: `https://flagcdn.com/w20/co.png` },
    { code: "PE", name: "Peru", dial_code: "+51", flag: "🇵🇪", flagUrl: `https://flagcdn.com/w20/pe.png` },
    { code: "SG", name: "Singapore", dial_code: "+65", flag: "🇸🇬", flagUrl: `https://flagcdn.com/w20/sg.png` },
    { code: "MY", name: "Malaysia", dial_code: "+60", flag: "🇲🇾", flagUrl: `https://flagcdn.com/w20/my.png` },
    { code: "ID", name: "Indonesia", dial_code: "+62", flag: "🇮🇩", flagUrl: `https://flagcdn.com/w20/id.png` },
    { code: "TH", name: "Thailand", dial_code: "+66", flag: "🇹🇭", flagUrl: `https://flagcdn.com/w20/th.png` },
    { code: "PH", name: "Philippines", dial_code: "+63", flag: "🇵🇭", flagUrl: `https://flagcdn.com/w20/ph.png` },
    { code: "VN", name: "Vietnam", dial_code: "+84", flag: "🇻🇳", flagUrl: `https://flagcdn.com/w20/vn.png` },
    { code: "RU", name: "Russia", dial_code: "+7", flag: "🇷🇺", flagUrl: `https://flagcdn.com/w20/ru.png` },
    { code: "TR", name: "Turkey", dial_code: "+90", flag: "🇹🇷", flagUrl: `https://flagcdn.com/w20/tr.png` },
    { code: "AE", name: "United Arab Emirates", dial_code: "+971", flag: "🇦🇪", flagUrl: `https://flagcdn.com/w20/ae.png` },
    { code: "SA", name: "Saudi Arabia", dial_code: "+966", flag: "🇸🇦", flagUrl: `https://flagcdn.com/w20/sa.png` },
    { code: "EG", name: "Egypt", dial_code: "+20", flag: "🇪🇬", flagUrl: `https://flagcdn.com/w20/eg.png` },
    { code: "NG", name: "Nigeria", dial_code: "+234", flag: "🇳🇬", flagUrl: `https://flagcdn.com/w20/ng.png` },
    { code: "KE", name: "Kenya", dial_code: "+254", flag: "🇰🇪", flagUrl: `https://flagcdn.com/w20/ke.png` },
    { code: "GH", name: "Ghana", dial_code: "+233", flag: "🇬🇭", flagUrl: `https://flagcdn.com/w20/gh.png` },
    { code: "ZW", name: "Zimbabwe", dial_code: "+263", flag: "🇿🇼", flagUrl: `https://flagcdn.com/w20/zw.png` },
    { code: "UA", name: "Ukraine", dial_code: "+380", flag: "🇺🇦", flagUrl: `https://flagcdn.com/w20/ua.png` },
    { code: "PL", name: "Poland", dial_code: "+48", flag: "🇵🇱", flagUrl: `https://flagcdn.com/w20/pl.png` },
    { code: "RO", name: "Romania", dial_code: "+40", flag: "🇷🇴", flagUrl: `https://flagcdn.com/w20/ro.png` },
    { code: "GR", name: "Greece", dial_code: "+30", flag: "🇬🇷", flagUrl: `https://flagcdn.com/w20/gr.png` },
    { code: "CZ", name: "Czech Republic", dial_code: "+420", flag: "🇨🇿", flagUrl: `https://flagcdn.com/w20/cz.png` },
    { code: "AF", name: "Afghanistan", dial_code: "+93", flag: "🇦🇫", flagUrl: `https://flagcdn.com/w20/af.png` },
    { code: "AL", name: "Albania", dial_code: "+355", flag: "🇦🇱", flagUrl: `https://flagcdn.com/w20/al.png` },
    { code: "DZ", name: "Algeria", dial_code: "+213", flag: "🇩🇿", flagUrl: `https://flagcdn.com/w20/dz.png` },
    { code: "AD", name: "Andorra", dial_code: "+376", flag: "🇦🇩", flagUrl: `https://flagcdn.com/w20/ad.png` },
    { code: "AO", name: "Angola", dial_code: "+244", flag: "🇦🇴", flagUrl: `https://flagcdn.com/w20/ao.png` },
    { code: "AG", name: "Antigua and Barbuda", dial_code: "+1268", flag: "🇦🇬", flagUrl: `https://flagcdn.com/w20/ag.png` },
    { code: "AM", name: "Armenia", dial_code: "+374", flag: "🇦🇲", flagUrl: `https://flagcdn.com/w20/am.png` },
    { code: "AZ", name: "Azerbaijan", dial_code: "+994", flag: "🇦🇿", flagUrl: `https://flagcdn.com/w20/az.png` },
    { code: "BS", name: "Bahamas", dial_code: "+1242", flag: "🇧🇸", flagUrl: `https://flagcdn.com/w20/bs.png` },
    { code: "BH", name: "Bahrain", dial_code: "+973", flag: "🇧🇭", flagUrl: `https://flagcdn.com/w20/bh.png` },
    { code: "BD", name: "Bangladesh", dial_code: "+880", flag: "🇧🇩", flagUrl: `https://flagcdn.com/w20/bd.png` },
    { code: "BB", name: "Barbados", dial_code: "+1246", flag: "🇧🇧", flagUrl: `https://flagcdn.com/w20/bb.png` },
    { code: "BY", name: "Belarus", dial_code: "+375", flag: "🇧🇾", flagUrl: `https://flagcdn.com/w20/by.png` },
    { code: "BZ", name: "Belize", dial_code: "+501", flag: "🇧🇿", flagUrl: `https://flagcdn.com/w20/bz.png` },
    { code: "BJ", name: "Benin", dial_code: "+229", flag: "🇧🇯", flagUrl: `https://flagcdn.com/w20/bj.png` },
    { code: "BT", name: "Bhutan", dial_code: "+975", flag: "🇧🇹", flagUrl: `https://flagcdn.com/w20/bt.png` },
    { code: "BO", name: "Bolivia", dial_code: "+591", flag: "🇧🇴", flagUrl: `https://flagcdn.com/w20/bo.png` },
    { code: "BA", name: "Bosnia and Herzegovina", dial_code: "+387", flag: "🇧🇦", flagUrl: `https://flagcdn.com/w20/ba.png` },
    { code: "BW", name: "Botswana", dial_code: "+267", flag: "🇧🇼", flagUrl: `https://flagcdn.com/w20/bw.png` },
    { code: "BN", name: "Brunei", dial_code: "+673", flag: "🇧🇳", flagUrl: `https://flagcdn.com/w20/bn.png` },
    { code: "BG", name: "Bulgaria", dial_code: "+359", flag: "🇧🇬", flagUrl: `https://flagcdn.com/w20/bg.png` },
    { code: "BF", name: "Burkina Faso", dial_code: "+226", flag: "🇧🇫", flagUrl: `https://flagcdn.com/w20/bf.png` },
    { code: "BI", name: "Burundi", dial_code: "+257", flag: "🇧🇮", flagUrl: `https://flagcdn.com/w20/bi.png` },
    { code: "KH", name: "Cambodia", dial_code: "+855", flag: "🇰🇭", flagUrl: `https://flagcdn.com/w20/kh.png` },
    { code: "CM", name: "Cameroon", dial_code: "+237", flag: "🇨🇲", flagUrl: `https://flagcdn.com/w20/cm.png` },
    { code: "CV", name: "Cape Verde", dial_code: "+238", flag: "🇨🇻", flagUrl: `https://flagcdn.com/w20/cv.png` },
    { code: "CF", name: "Central African Republic", dial_code: "+236", flag: "🇨🇫", flagUrl: `https://flagcdn.com/w20/cf.png` },
    { code: "TD", name: "Chad", dial_code: "+235", flag: "🇹🇩", flagUrl: `https://flagcdn.com/w20/td.png` },
    { code: "KM", name: "Comoros", dial_code: "+269", flag: "🇰🇲", flagUrl: `https://flagcdn.com/w20/km.png` },
    { code: "CD", name: "Democratic Republic of the Congo", dial_code: "+243", flag: "🇨🇩", flagUrl: `https://flagcdn.com/w20/cd.png` },
    { code: "CG", name: "Republic of the Congo", dial_code: "+242", flag: "🇨🇬", flagUrl: `https://flagcdn.com/w20/cg.png` },
    { code: "CR", name: "Costa Rica", dial_code: "+506", flag: "🇨🇷", flagUrl: `https://flagcdn.com/w20/cr.png` },
    { code: "CI", name: "Côte d'Ivoire", dial_code: "+225", flag: "🇨🇮", flagUrl: `https://flagcdn.com/w20/ci.png` },
    { code: "HR", name: "Croatia", dial_code: "+385", flag: "🇭🇷", flagUrl: `https://flagcdn.com/w20/hr.png` },
    { code: "CU", name: "Cuba", dial_code: "+53", flag: "🇨🇺", flagUrl: `https://flagcdn.com/w20/cu.png` },
    { code: "CY", name: "Cyprus", dial_code: "+357", flag: "🇨🇾", flagUrl: `https://flagcdn.com/w20/cy.png` },
    { code: "DJ", name: "Djibouti", dial_code: "+253", flag: "🇩🇯", flagUrl: `https://flagcdn.com/w20/dj.png` },
    { code: "DM", name: "Dominica", dial_code: "+1767", flag: "🇩🇲", flagUrl: `https://flagcdn.com/w20/dm.png` },
    { code: "DO", name: "Dominican Republic", dial_code: "+1809", flag: "🇩🇴", flagUrl: `https://flagcdn.com/w20/do.png` },
    { code: "EC", name: "Ecuador", dial_code: "+593", flag: "🇪🇨", flagUrl: `https://flagcdn.com/w20/ec.png` },
    { code: "SV", name: "El Salvador", dial_code: "+503", flag: "🇸🇻", flagUrl: `https://flagcdn.com/w20/sv.png` },
    { code: "GQ", name: "Equatorial Guinea", dial_code: "+240", flag: "🇬🇶", flagUrl: `https://flagcdn.com/w20/gq.png` },
    { code: "ER", name: "Eritrea", dial_code: "+291", flag: "🇪🇷", flagUrl: `https://flagcdn.com/w20/er.png` },
    { code: "EE", name: "Estonia", dial_code: "+372", flag: "🇪🇪", flagUrl: `https://flagcdn.com/w20/ee.png` },
    { code: "ET", name: "Ethiopia", dial_code: "+251", flag: "🇪🇹", flagUrl: `https://flagcdn.com/w20/et.png` },
    { code: "FJ", name: "Fiji", dial_code: "+679", flag: "🇫🇯", flagUrl: `https://flagcdn.com/w20/fj.png` },
    { code: "GA", name: "Gabon", dial_code: "+241", flag: "🇬🇦", flagUrl: `https://flagcdn.com/w20/ga.png` },
    { code: "GM", name: "Gambia", dial_code: "+220", flag: "🇬🇲", flagUrl: `https://flagcdn.com/w20/gm.png` },
    { code: "GE", name: "Georgia", dial_code: "+995", flag: "🇬🇪", flagUrl: `https://flagcdn.com/w20/ge.png` },
    { code: "GI", name: "Gibraltar", dial_code: "+350", flag: "🇬🇮", flagUrl: `https://flagcdn.com/w20/gi.png` },
    { code: "GD", name: "Grenada", dial_code: "+1473", flag: "🇬🇩", flagUrl: `https://flagcdn.com/w20/gd.png` },
    { code: "GT", name: "Guatemala", dial_code: "+502", flag: "🇬🇹", flagUrl: `https://flagcdn.com/w20/gt.png` },
    { code: "GN", name: "Guinea", dial_code: "+224", flag: "🇬🇳", flagUrl: `https://flagcdn.com/w20/gn.png` },
    { code: "GW", name: "Guinea-Bissau", dial_code: "+245", flag: "🇬🇼", flagUrl: `https://flagcdn.com/w20/gw.png` },
    { code: "GY", name: "Guyana", dial_code: "+592", flag: "🇬🇾", flagUrl: `https://flagcdn.com/w20/gy.png` },
    { code: "HT", name: "Haiti", dial_code: "+509", flag: "🇭🇹", flagUrl: `https://flagcdn.com/w20/ht.png` },
    { code: "HN", name: "Honduras", dial_code: "+504", flag: "🇭🇳", flagUrl: `https://flagcdn.com/w20/hn.png` },
    { code: "HU", name: "Hungary", dial_code: "+36", flag: "🇭🇺", flagUrl: `https://flagcdn.com/w20/hu.png` },
    { code: "IS", name: "Iceland", dial_code: "+354", flag: "🇮🇸", flagUrl: `https://flagcdn.com/w20/is.png` },
    { code: "IR", name: "Iran", dial_code: "+98", flag: "🇮🇷", flagUrl: `https://flagcdn.com/w20/ir.png` },
    { code: "IQ", name: "Iraq", dial_code: "+964", flag: "🇮🇶", flagUrl: `https://flagcdn.com/w20/iq.png` },
    { code: "IE", name: "Ireland", dial_code: "+353", flag: "🇮🇪", flagUrl: `https://flagcdn.com/w20/ie.png` },
    { code: "IL", name: "Israel", dial_code: "+972", flag: "🇮🇱", flagUrl: `https://flagcdn.com/w20/il.png` },
    { code: "JM", name: "Jamaica", dial_code: "+1876", flag: "🇯🇲", flagUrl: `https://flagcdn.com/w20/jm.png` },
    { code: "JO", name: "Jordan", dial_code: "+962", flag: "🇯🇴", flagUrl: `https://flagcdn.com/w20/jo.png` },
    { code: "KZ", name: "Kazakhstan", dial_code: "+7", flag: "🇰🇿", flagUrl: `https://flagcdn.com/w20/kz.png` },
    { code: "KW", name: "Kuwait", dial_code: "+965", flag: "🇰🇼", flagUrl: `https://flagcdn.com/w20/kw.png` },
    { code: "KG", name: "Kyrgyzstan", dial_code: "+996", flag: "🇰🇬", flagUrl: `https://flagcdn.com/w20/kg.png` },
    { code: "LA", name: "Laos", dial_code: "+856", flag: "🇱🇦", flagUrl: `https://flagcdn.com/w20/la.png` },
    { code: "LV", name: "Latvia", dial_code: "+371", flag: "🇱🇻", flagUrl: `https://flagcdn.com/w20/lv.png` },
    { code: "LB", name: "Lebanon", dial_code: "+961", flag: "🇱🇧", flagUrl: `https://flagcdn.com/w20/lb.png` },
    { code: "LS", name: "Lesotho", dial_code: "+266", flag: "🇱🇸", flagUrl: `https://flagcdn.com/w20/ls.png` },
    { code: "LR", name: "Liberia", dial_code: "+231", flag: "🇱🇷", flagUrl: `https://flagcdn.com/w20/lr.png` },
    { code: "LY", name: "Libya", dial_code: "+218", flag: "🇱🇾", flagUrl: `https://flagcdn.com/w20/ly.png` },
    { code: "LI", name: "Liechtenstein", dial_code: "+423", flag: "🇱🇮", flagUrl: `https://flagcdn.com/w20/li.png` },
    { code: "LT", name: "Lithuania", dial_code: "+370", flag: "🇱🇹", flagUrl: `https://flagcdn.com/w20/lt.png` },
    { code: "LU", name: "Luxembourg", dial_code: "+352", flag: "🇱🇺", flagUrl: `https://flagcdn.com/w20/lu.png` },
    { code: "MK", name: "North Macedonia", dial_code: "+389", flag: "🇲🇰", flagUrl: `https://flagcdn.com/w20/mk.png` },
    { code: "MG", name: "Madagascar", dial_code: "+261", flag: "🇲🇬", flagUrl: `https://flagcdn.com/w20/mg.png` },
    { code: "MW", name: "Malawi", dial_code: "+265", flag: "🇲🇼", flagUrl: `https://flagcdn.com/w20/mw.png` },
    { code: "MV", name: "Maldives", dial_code: "+960", flag: "🇲🇻", flagUrl: `https://flagcdn.com/w20/mv.png` },
    { code: "ML", name: "Mali", dial_code: "+223", flag: "🇲🇱", flagUrl: `https://flagcdn.com/w20/ml.png` },
    { code: "MT", name: "Malta", dial_code: "+356", flag: "🇲🇹", flagUrl: `https://flagcdn.com/w20/mt.png` },
    { code: "MH", name: "Marshall Islands", dial_code: "+692", flag: "🇲🇭", flagUrl: `https://flagcdn.com/w20/mh.png` },
    { code: "MR", name: "Mauritania", dial_code: "+222", flag: "🇲🇷", flagUrl: `https://flagcdn.com/w20/mr.png` },
    { code: "MU", name: "Mauritius", dial_code: "+230", flag: "🇲🇺", flagUrl: `https://flagcdn.com/w20/mu.png` },
    { code: "FM", name: "Micronesia", dial_code: "+691", flag: "🇫🇲", flagUrl: `https://flagcdn.com/w20/fm.png` },
    { code: "MD", name: "Moldova", dial_code: "+373", flag: "🇲🇩", flagUrl: `https://flagcdn.com/w20/md.png` },
    { code: "MC", name: "Monaco", dial_code: "+377", flag: "🇲🇨", flagUrl: `https://flagcdn.com/w20/mc.png` },
    { code: "MN", name: "Mongolia", dial_code: "+976", flag: "🇲🇳", flagUrl: `https://flagcdn.com/w20/mn.png` },
    { code: "ME", name: "Montenegro", dial_code: "+382", flag: "🇲🇪", flagUrl: `https://flagcdn.com/w20/me.png` },
    { code: "MA", name: "Morocco", dial_code: "+212", flag: "🇲🇦", flagUrl: `https://flagcdn.com/w20/ma.png` },
    { code: "MZ", name: "Mozambique", dial_code: "+258", flag: "🇲🇿", flagUrl: `https://flagcdn.com/w20/mz.png` },
    { code: "MM", name: "Myanmar", dial_code: "+95", flag: "🇲🇲", flagUrl: `https://flagcdn.com/w20/mm.png` },
    { code: "NA", name: "Namibia", dial_code: "+264", flag: "🇳🇦", flagUrl: `https://flagcdn.com/w20/na.png` },
    { code: "NR", name: "Nauru", dial_code: "+674", flag: "🇳🇷", flagUrl: `https://flagcdn.com/w20/nr.png` },
    { code: "NP", name: "Nepal", dial_code: "+977", flag: "🇳🇵", flagUrl: `https://flagcdn.com/w20/np.png` },
    { code: "NI", name: "Nicaragua", dial_code: "+505", flag: "🇳🇮", flagUrl: `https://flagcdn.com/w20/ni.png` },
    { code: "NE", name: "Niger", dial_code: "+227", flag: "🇳🇪", flagUrl: `https://flagcdn.com/w20/ne.png` },
    { code: "OM", name: "Oman", dial_code: "+968", flag: "🇴🇲", flagUrl: `https://flagcdn.com/w20/om.png` },
    { code: "PK", name: "Pakistan", dial_code: "+92", flag: "🇵🇰", flagUrl: `https://flagcdn.com/w20/pk.png` },
    { code: "PW", name: "Palau", dial_code: "+680", flag: "🇵🇼", flagUrl: `https://flagcdn.com/w20/pw.png` },
    { code: "PS", name: "Palestine", dial_code: "+970", flag: "🇵🇸", flagUrl: `https://flagcdn.com/w20/ps.png` },
    { code: "PA", name: "Panama", dial_code: "+507", flag: "🇵🇦", flagUrl: `https://flagcdn.com/w20/pa.png` },
    { code: "PG", name: "Papua New Guinea", dial_code: "+675", flag: "🇵🇬", flagUrl: `https://flagcdn.com/w20/pg.png` },
    { code: "PY", name: "Paraguay", dial_code: "+595", flag: "🇵🇾", flagUrl: `https://flagcdn.com/w20/py.png` },
    { code: "QA", name: "Qatar", dial_code: "+974", flag: "🇶🇦", flagUrl: `https://flagcdn.com/w20/qa.png` },
    { code: "RW", name: "Rwanda", dial_code: "+250", flag: "🇷🇼", flagUrl: `https://flagcdn.com/w20/rw.png` },
    { code: "KN", name: "Saint Kitts and Nevis", dial_code: "+1869", flag: "🇰🇳", flagUrl: `https://flagcdn.com/w20/kn.png` },
    { code: "LC", name: "Saint Lucia", dial_code: "+1758", flag: "🇱🇨", flagUrl: `https://flagcdn.com/w20/lc.png` },
    { code: "VC", name: "Saint Vincent and the Grenadines", dial_code: "+1784", flag: "🇻🇨", flagUrl: `https://flagcdn.com/w20/vc.png` },
    { code: "WS", name: "Samoa", dial_code: "+685", flag: "🇼🇸", flagUrl: `https://flagcdn.com/w20/ws.png` },
    { code: "SM", name: "San Marino", dial_code: "+378", flag: "🇸🇲", flagUrl: `https://flagcdn.com/w20/sm.png` },
    { code: "ST", name: "São Tomé and Príncipe", dial_code: "+239", flag: "🇸🇹", flagUrl: `https://flagcdn.com/w20/st.png` },
    { code: "SN", name: "Senegal", dial_code: "+221", flag: "🇸🇳", flagUrl: `https://flagcdn.com/w20/sn.png` },
    { code: "RS", name: "Serbia", dial_code: "+381", flag: "🇷🇸", flagUrl: `https://flagcdn.com/w20/rs.png` },
    { code: "SC", name: "Seychelles", dial_code: "+248", flag: "🇸🇨", flagUrl: `https://flagcdn.com/w20/sc.png` },
    { code: "SL", name: "Sierra Leone", dial_code: "+232", flag: "🇸🇱", flagUrl: `https://flagcdn.com/w20/sl.png` },
    { code: "SK", name: "Slovakia", dial_code: "+421", flag: "🇸🇰", flagUrl: `https://flagcdn.com/w20/sk.png` },
    { code: "SI", name: "Slovenia", dial_code: "+386", flag: "🇸🇮", flagUrl: `https://flagcdn.com/w20/si.png` },
    { code: "SB", name: "Solomon Islands", dial_code: "+677", flag: "🇸🇧", flagUrl: `https://flagcdn.com/w20/sb.png` },
    { code: "SO", name: "Somalia", dial_code: "+252", flag: "🇸🇴", flagUrl: `https://flagcdn.com/w20/so.png` },
    { code: "SS", name: "South Sudan", dial_code: "+211", flag: "🇸🇸", flagUrl: `https://flagcdn.com/w20/ss.png` },
    { code: "LK", name: "Sri Lanka", dial_code: "+94", flag: "🇱🇰", flagUrl: `https://flagcdn.com/w20/lk.png` },
    { code: "SD", name: "Sudan", dial_code: "+249", flag: "🇸🇩", flagUrl: `https://flagcdn.com/w20/sd.png` },
    { code: "SR", name: "Suriname", dial_code: "+597", flag: "🇸🇷", flagUrl: `https://flagcdn.com/w20/sr.png` },
    { code: "SZ", name: "Eswatini", dial_code: "+268", flag: "🇸🇿", flagUrl: `https://flagcdn.com/w20/sz.png` },
    { code: "SY", name: "Syria", dial_code: "+963", flag: "🇸🇾", flagUrl: `https://flagcdn.com/w20/sy.png` },
    { code: "TJ", name: "Tajikistan", dial_code: "+992", flag: "🇹🇯", flagUrl: `https://flagcdn.com/w20/tj.png` },
    { code: "TZ", name: "Tanzania", dial_code: "+255", flag: "🇹🇿", flagUrl: `https://flagcdn.com/w20/tz.png` },
    { code: "TL", name: "Timor-Leste", dial_code: "+670", flag: "🇹🇱", flagUrl: `https://flagcdn.com/w20/tl.png` },
    { code: "TG", name: "Togo", dial_code: "+228", flag: "🇹🇬", flagUrl: `https://flagcdn.com/w20/tg.png` },
    { code: "TO", name: "Tonga", dial_code: "+676", flag: "🇹🇴", flagUrl: `https://flagcdn.com/w20/to.png` },
    { code: "TT", name: "Trinidad and Tobago", dial_code: "+1868", flag: "🇹🇹", flagUrl: `https://flagcdn.com/w20/tt.png` },
    { code: "TN", name: "Tunisia", dial_code: "+216", flag: "🇹🇳", flagUrl: `https://flagcdn.com/w20/tn.png` },
    { code: "TM", name: "Turkmenistan", dial_code: "+993", flag: "🇹🇲", flagUrl: `https://flagcdn.com/w20/tm.png` },
    { code: "TV", name: "Tuvalu", dial_code: "+688", flag: "🇹🇻", flagUrl: `https://flagcdn.com/w20/tv.png` },
    { code: "UG", name: "Uganda", dial_code: "+256", flag: "🇺🇬", flagUrl: `https://flagcdn.com/w20/ug.png` },
    { code: "UY", name: "Uruguay", dial_code: "+598", flag: "🇺🇾", flagUrl: `https://flagcdn.com/w20/uy.png` },
    { code: "UZ", name: "Uzbekistan", dial_code: "+998", flag: "🇺🇿", flagUrl: `https://flagcdn.com/w20/uz.png` },
    { code: "VU", name: "Vanuatu", dial_code: "+678", flag: "🇻🇺", flagUrl: `https://flagcdn.com/w20/vu.png` },
    { code: "VA", name: "Vatican City", dial_code: "+379", flag: "🇻🇦", flagUrl: `https://flagcdn.com/w20/va.png` },
    { code: "VE", name: "Venezuela", dial_code: "+58", flag: "🇻🇪", flagUrl: `https://flagcdn.com/w20/ve.png` },
    { code: "YE", name: "Yemen", dial_code: "+967", flag: "🇾🇪", flagUrl: `https://flagcdn.com/w20/ye.png` },
    { code: "ZM", name: "Zambia", dial_code: "+260", flag: "🇿🇲", flagUrl: `https://flagcdn.com/w20/zm.png` },
  ];
  
  export default countries;